# Generated by Django 2.2.7 on 2019-11-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round', models.CharField(max_length=100)),
                ('Year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sponsor', models.CharField(max_length=100)),
                ('GameName', models.CharField(max_length=100)),
                ('RealName', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Earnings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Wins', models.IntegerField()),
                ('Losses', models.IntegerField()),
                ('Draws', models.IntegerField()),
                ('Region', models.CharField(max_length=100)),
                ('TotalWinnings', models.IntegerField()),
                ('Sponsor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('TournamentName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Year', models.DateTimeField(verbose_name='Start Date')),
                ('Location', models.CharField(max_length=100)),
                ('PrizeMoney', models.IntegerField()),
                ('Winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGames',
            fields=[
                ('GameName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Developer', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlaysIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Match')),
                ('TeamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlaysGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.VideoGames')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Team'),
        ),
    ]
