# Generated by Django 2.2.7 on 2019-11-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playsin',
            name='MatchID',
        ),
        migrations.RemoveField(
            model_name='playsin',
            name='TeamName',
        ),
        migrations.RemoveField(
            model_name='players',
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='PlaysIn',
        ),
    ]
