# Generated by Django 2.2.7 on 2019-11-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qpage', '0002_auto_20191130_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round', models.CharField(max_length=100)),
                ('Year', models.DateField()),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlaysIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Match')),
                ('TeamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qpage.Team')),
            ],
        ),
    ]
